#!/usr/bin/env python3
# Generates config.js from environment variables at build time (Railway) — mirrors juicebox.money's
# env-var names for the shared services so values copy straight across. Locally, config.js is
# gitignored and hand-written; this only runs in the deploy build (see railway.json).
#
# ponytail: a single build step, no bundler. The client has no build system of its own — it just
# reads window.STICKY_CONFIG — so this Python emitter IS the "build".
import json, os

def env(*names, default=""):
    for n in names:
        v = os.environ.get(n)
        if v is not None and v.strip():
            return v.strip()
    return default

# Dwellir archive hostnames, same map juicebox.money uses. Given a key, every chain gets an RPC URL.
# All four networks on prod and testnet are served every deploy, like juicebox.money.
DWELLIR = {
    1: "api-ethereum-mainnet.n.dwellir.com",
    10: "api-optimism-mainnet-archive.n.dwellir.com",
    8453: "api-base-mainnet-archive.n.dwellir.com",
    42161: "api-arbitrum-mainnet-archive.n.dwellir.com",
    11155111: "api-ethereum-sepolia.n.dwellir.com",
    11155420: "api-optimism-sepolia.n.dwellir.com",
    84532: "api-base-sepolia-archive.n.dwellir.com",
    421614: "api-arbitrum-sepolia.n.dwellir.com",
}
ALL_CHAINS = list(DWELLIR.keys())

dwellir_key = env("NEXT_PUBLIC_DWELLIR_API_KEY", "STICKY_DWELLIR_API_KEY")
def rpc_for(chain_id):
    host = DWELLIR.get(chain_id)
    if host and dwellir_key:
        return f"https://{host}/{dwellir_key}"
    return env(f"STICKY_RPC_{chain_id}")  # explicit per-chain override, else empty (client falls back to a public RPC)

default_chain = int(env("STICKY_DEFAULT_CHAIN", default="1"))

# One deployer/autoStick address across chains (deterministic deploy) unless per-chain overrides exist.
deployer = env("STICKY_DEPLOYER")
autostick = env("STICKY_AUTOSTICK_ADAPTER")

chains = {}
for cid in ALL_CHAINS:
    entry = {"rpcUrl": rpc_for(cid)}
    d = env(f"STICKY_DEPLOYER_{cid}", default=deployer)
    a = env(f"STICKY_AUTOSTICK_ADAPTER_{cid}", default=autostick)
    if d:
        entry["deployer"] = d
    if a:
        entry["autoStickAdapter"] = a
    chains[str(cid)] = entry

# ENS reverse-resolution runs on Ethereum mainnet — reuse the Dwellir mainnet URL when we have a key.
ens_rpc = env("STICKY_ENS_RPC") or rpc_for(1) or "https://ethereum-rpc.publicnode.com"

config = {
    "rpcUrl": rpc_for(default_chain),
    "ensRpc": ens_rpc,
    "deployer": deployer,
    "projectId": int(env("STICKY_PROJECT_ID", default="0")) or None,
    "fromBlock": env("STICKY_FROM_BLOCK", default="earliest"),
    "distributor": env("STICKY_DISTRIBUTOR"),
    "pockets": env("STICKY_POCKETS"),
    "autoStickAdapter": autostick,
    "chains": chains,
    # Threaded through for when the client wires them; mirrors juicebox.money's names.
    "bendystrawUrl": env("NEXT_PUBLIC_BENDYSTRAW_URL", default="https://bendystraw.up.railway.app"),
    "testnetBendystrawUrl": env("NEXT_PUBLIC_TESTNET_BENDYSTRAW_URL", default="https://testnet.bendystraw.xyz"),
    "paraApiKey": env("NEXT_PUBLIC_PARA_API_KEY", "STICKY_PARA_API_KEY"),
    "paraEnv": env("NEXT_PUBLIC_PARA_ENV", "STICKY_PARA_ENV", default="PROD"),
}

with open("config.js", "w") as f:
    f.write("// Generated by build-config.py from environment variables. Do not edit — see railway.json.\n")
    f.write("window.STICKY_CONFIG = " + json.dumps(config, indent=2) + ";\n")

print(f"config.js generated: {len(ALL_CHAINS)} chains (prod+testnet), "
      f"dwellir={'set' if dwellir_key else 'MISSING — public RPC fallback'}, "
      f"deployer={'set' if deployer else 'MISSING'}")
